In [4]:
import numpy as np
x =np.array([1 ,2, 4, 5])
print(x)
print(type(x))

[1 2 4 5]
<class 'numpy.ndarray'>


# %timeit---oneline

In [11]:
%timeit [j**4 for j in range(1,9)]

1.55 μs ± 105 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [12]:
import numpy as np
%timeit np.arange(1,9)**4

3.84 μs ± 63.5 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [14]:
import numpy as np
%timeit np.arange(1,9)**4

9.24 μs ± 451 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


# ARRAY

In [17]:
x = [1,3,4,5]
y = np.array(x)
print(y)
print(type(y))

[1 3 4 5]
<class 'numpy.ndarray'>


# types od array

# Dimensional array

In [29]:

x = [1,3,4,5]
y = np.array(x)
print(y)
print(type(y))
print(y.ndim)#.ndim--- array kitna Dimensional array hai




[1 3 4 5]
<class 'numpy.ndarray'>
1


In [30]:
l = []#empty
for i in range(1,10):# loop chala hai
    int_value=int(input("Enter the number:"))
    l.append(int_value)# add kiya hu l

import numpy as np
print(np.array(l))                  

Enter the number: 1
Enter the number: 2
Enter the number: 3
Enter the number: 6
Enter the number: 7
Enter the number: 6
Enter the number: 5
Enter the number: 4
Enter the number: 8


[1 2 3 6 7 6 5 4 8]


# 2D array

In [32]:
x = np.array([[1,2,3,4],[6,7,8,9]])
print(x)
print(x.ndim)# kitna array hai

[[1 2 3 4]
 [6 7 8 9]]
2


# 3D array

In [33]:
x = np.array([[[1,2,3,4],[6,7,8,9],[8,9,4,2]]])
print(x)
print(x.ndim)# kitna array hai

[[[1 2 3 4]
  [6 7 8 9]
  [8 9 4 2]]]
3


# multi Dimensional array¶

In [35]:
x = np.array([1,2,3,4],ndmin= 10)
print(x)
print(x.ndim)


[[[[[[[[[[1 2 3 4]]]]]]]]]]
10


# special numpy array

# zeros array

In [10]:
import numpy as np

ar_zero = np.zeros(4)
print()
ar_zero1 = np.zeros((3, 4))# row column
print()
print(ar_zero1)
print(ar_zero)



[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[0. 0. 0. 0.]


# ones Array

In [11]:
import numpy as np
ar_one = np.ones(4)
print(ar_one)

[1. 1. 1. 1.]


# 3 Empty

In [12]:
import numpy as np
ar_em = np.empty(4)
print(ar_em)

[1. 1. 1. 1.]


# iv RAnge

In [15]:

import numpy as np
ar_range = np.arange(6)
print(ar_range)

[0 1 2 3 4 5]


# v Diagonal elemnent

In [16]:
import numpy as np
ar_dia = np.eye(3)
print(ar_dia)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [17]:
import numpy as np
ar_dia = np.eye(4,5)
print(ar_dia)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]


# vi linspace

In [18]:
ar_lin = np.linspace(1,10,num= 5)# space decide karta hai kitna elemnet ho
print(ar_lin)

[ 1.    3.25  5.5   7.75 10.  ]


# CREATE NUMPY ARRAY WITH RANDOM NUMBER

# i rand

In [19]:
import numpy as np
var = np.random.rand(4)
print(var)

[0.73467799 0.51130176 0.07963431 0.92409985]


In [22]:
import numpy as np
var = np.random.rand(4,8)
print(var)

[[0.38500426 0.0103256  0.61488441 0.39331627 0.58673765 0.55490612
  0.35111489 0.48984456]
 [0.16598166 0.20934438 0.49161172 0.61170571 0.23688785 0.28623429
  0.08129924 0.29181136]
 [0.30823062 0.02168297 0.26989565 0.3486919  0.86752626 0.97717654
  0.64656522 0.87308325]
 [0.59826579 0.06489861 0.12463817 0.60804583 0.34714723 0.0721807
  0.89762874 0.91018961]]


# ii randn()----pastive and negative

In [21]:
import numpy as np
var = np.random.randn(4,8)
print(var)

[[-0.61069198  0.80352355  0.17155759 -0.59048301  0.41225073 -1.02267064
   1.11039796 -1.45250173]
 [ 0.78783073  2.21536802  1.38041992  0.60735594 -1.48484296 -0.88741713
   0.82965652  0.42422149]
 [ 0.72917231 -1.32319195 -1.00448966 -0.76037205 -0.89874594 -0.62861887
  -1.08022909 -3.04506523]
 [-1.68434635 -1.93509949 -0.21624947 -0.53558201 -1.28879976  0.52007475
  -1.02379164 -1.05607539]]


# iv ranf()---1 include not

In [26]:
import numpy as np
var = np.random.ranf(4)# two colomn row not allow
print(var)

[0.66094149 0.97618615 0.16411598 0.11149476]


# SHAPE AND RESHAPE IN NUMPY

# shape (ye baata hai row column kitna hai)

In [27]:
x = np.array([[1,2,3,4],[6,7,8,9]])
print(x)
print(x.ndim)# kitna array hai
print(x.shape)

[[1 2 3 4]
 [6 7 8 9]]
2
(2, 4)


# ii multi array

In [30]:
x = np.array([1,2,3,4],ndmin = 4)
print(x)
print(x.ndim)# kitna array hai
print(x.shape)

[[[[1 2 3 4]]]]
4
(1, 1, 1, 4)


# 2 RESHAPE

In [31]:
VAR = np.array([1,2,3,5,6,8])
print(VAR.reshape(3,2))

[[1 2]
 [3 5]
 [6 8]]


In [38]:
VAR = np.array([1,2,3,5,6,8])
print(VAR.reshape(2,3))

[[1 2 3]
 [5 6 8]]


In [39]:
VAR = np.array([1,2,3,5,6,8,6,9,5])
print(VAR.reshape(3,3))

[[1 2 3]
 [5 6 8]
 [6 9 5]]


In [40]:
VAR = np.array([1,2,3,5,6,8,6,9,5,1,2,3,4,5,6,7,8,5])
print(VAR.reshape(3,2,3))#block row column

[[[1 2 3]
  [5 6 8]]

 [[6 9 5]
  [1 2 3]]

 [[4 5 6]
  [7 8 5]]]


# ARITHMETIC OPERATIONS

# i addtion

In [44]:
import numpy as np
var= np.array([1,2,3,4])
diff=var+3
print(diff)

[4 5 6 7]


In [45]:
import numpy as np
var= np.array([1,2,3,4])
var1=([1,2,3,4])
diff=var+var1
print(diff)

[2 4 6 8]


# ii subtract

In [46]:
import numpy as np
var= np.array([1,2,3,4])
diff=var-3
print(diff)

[-2 -1  0  1]


In [50]:
import numpy as np
var= np.array([1,2,3,4])
var1=([1,2,3,4])
diff=var-var1
print(diff)

[0 0 0 0]


# iii multiple

In [51]:
import numpy as np
var= np.array([1,2,3,4])
diff=var*3
print(diff)

[ 3  6  9 12]


In [52]:
import numpy as np
var= np.array([1,2,3,4])
var1=([1,2,3,4])
diff=var*var1
print(diff)

[ 1  4  9 16]


# iv divide

In [53]:
import numpy as np
var= np.array([1,2,3,4])
diff=var/3
print(diff)

[0.33333333 0.66666667 1.         1.33333333]


In [54]:
import numpy as np
var= np.array([1,2,3,4])
var1=([1,2,3,4])
diff=var/var1
print(diff)

[1. 1. 1. 1.]


# v mod

In [55]:
import numpy as np
var= np.array([1,2,3,4])
diff=var%3
print(diff)

[1 2 0 1]


In [59]:
import numpy as np
var= np.array([1,2,3,4])
var1=([1,2,3,4])
diff=var%var1
print(diff)

[0 0 0 0]


# iv power**

In [60]:
import numpy as np
var= np.array([1,2,3,4])
diff=var**3
print(diff)

[ 1  8 27 64]


In [61]:
import numpy as np
var= np.array([1,2,3,4])
var1=([1,2,3,4])
diff=var**var1
print(diff)

[  1   4  27 256]


# BOARDCASTING WITH NUMPY ARRAY

In [63]:
 import numpy as np
var= np.array([1,2,3,4])
var1=([1,2,3,4])
diff=var+var1
print(diff)


[2 4 6 8]


# i indexing 

In [64]:
 import numpy as np
var= np.array([1,2,3,4])
print(var[1])

2


In [66]:
 import numpy as np
var= np.array([1,2,3,4])
print(var[-1])

4


# ii 2D array indexing

In [70]:
import numpy as np
var= np.array([[1,2,3,4],[2,4,6,8]])
print(var)
print()# space
print(var.ndim)
print()
print(var[0,3])#  0 indexing ,number

[[1 2 3 4]
 [2 4 6 8]]

2

4


# iii 3D array

In [81]:
import numpy as np
var2= np.array([[[1,2],[3,4]]])
print(var2.ndim)

print(var2[0,1,0])
print(var2[0,1,1])# 0 row kitne number 1[3,4] indexing 1[4]

3
3
4


# slicing

# sclicing

In [23]:
import numpy as np
var = np.array([9,8,7,6,5,4,3])
print("9 to 4:",var[:5])
print("3 to 9:",var[::2])
print("3 to 9:",var[1:5:2])
print("3 to 9:",var[::])
print("3 to 9:",var[-1:-5:2])





9 to 4: [9 8 7 6 5]
3 to 9: [9 7 5 3]
3 to 9: [8 6]
3 to 9: [9 8 7 6 5 4 3]
3 to 9: []


In [40]:
import numpy as np
var = np.array([[[1,2,3,4],
                 [2,4,6,8],
                 [9,8,7,6]]])

print(var[0,2])          # last row -> [9 8 7 6]
print("Row 2:", var[0,1,:])   # 2nd row -> [2 4 6 8]
print("row 3:",var[0,2,1:3])#0 row 2 column 1se start 3 tk chahiye


[9 8 7 6]
Row 2: [2 4 6 8]
row 3: [8 7]


# iterating numpy array

In [41]:
x= np.array([1,2,3,4,5])
for i in x:
    print(i)

1
2
3
4
5


In [47]:
import numpy as np
x1= np.array([[1,2,3,4,5],[4,5,7,8,9]])
for j in x1:
    print(j)
    print()

for k in x1:
    for l in k:
        print(l)

[1 2 3 4 5]

[4 5 7 8 9]

1
2
3
4
5
4
5
7
8
9


In [50]:
import numpy as np
x1= np.array([[[1,2,3,4,5],[4,5,7,8,9]]])# jitna hoga utna loop chalega 
print(x1)
print()
for i in x1:
    for j in i:
        for k in j:
             print(k)

[[[1 2 3 4 5]
  [4 5 7 8 9]]]

1
2
3
4
5
4
5
7
8
9


In [54]:
# [nditer ]ek baar me sab ho jayega baar for loop nhi lagna padega
import numpy as np
x1= np.array([[[1,2,3,4,5],[4,5,7,8,9]]])# jitna hoga utna loop chalega 
print(x1)
for i in np.nditer(x1,flags=['buffered'],op_dtypes=['S']):#flags=['buffered']space banta hai

     print(i)

[[[1 2 3 4 5]
  [4 5 7 8 9]]]
b'1'
b'2'
b'3'
b'4'
b'5'
b'4'
b'5'
b'7'
b'8'
b'9'


In [58]:
import numpy as np
x1= np.array([[[1,2,3,4,5],[4,5,7,8,9]]])# jitna hoga utna loop chalega 
print(x1)
for i in np.ndenumerate(x1):# numer  aaya indexing
    print(i)

[[[1 2 3 4 5]
  [4 5 7 8 9]]]
((0, 0, 0), 1)
((0, 0, 1), 2)
((0, 0, 2), 3)
((0, 0, 3), 4)
((0, 0, 4), 5)
((0, 1, 0), 4)
((0, 1, 1), 5)
((0, 1, 2), 7)
((0, 1, 3), 8)
((0, 1, 4), 9)


# COPY VS VIEW IN NUMPY ARRAYS

# copy

In [70]:
import numpy as np
x1= np.array([1,2,3,4,5])
print(x1)

var = x1.copy()
x1[2]= 40
print("copy:", var)

[1 2 3 4 5]
copy: [1 2 3 4 5]


In [71]:
import numpy as np
x1= np.array([1,2,3,4,5])
print(x1)

var = x1.view()
x1[2]= 40
print("view:", var)

[1 2 3 4 5]
view: [ 1  2 40  4  5]


# join s split function

# i 1D array

In [4]:
import numpy as np
var1= np.array([1,2,3,4,5])
var2= np.array([7,8,7,8,4])
ar=np.concatenate((var1,var2))
print(ar)

[1 2 3 4 5 7 8 7 8 4]


# ii 2D array

In [10]:
# 1 is row wise
# 0 is column wise
import numpy as np
var1= np.array([[1,2],[3,4]])
var2= np.array([[7,8],[7,8]])
ar=np.concatenate((var1,var2),axis=1)
print(var1)

print()
print(var2)
print()

print(ar)

[[1 2]
 [3 4]]

[[7 8]
 [7 8]]

[[1 2 7 8]
 [3 4 7 8]]


In [11]:
import numpy as np
var1= np.array([[1,2],[3,4]])
var2= np.array([[7,8],[7,8]])
ar=np.concatenate((var1,var2),axis=0)
print(var1)

print()
print(var2)
print()

print(ar)

[[1 2]
 [3 4]]

[[7 8]
 [7 8]]

[[1 2]
 [3 4]
 [7 8]
 [7 8]]


In [12]:
import numpy as np
var1= np.array([[1,2],[3,4]])
var2= np.array([[7,8],[7,8]])
ar=np.hstack((var1,var2))# h stack is horizental
print(var1)

print()
print(var2)
print()

print(ar)

[[1 2]
 [3 4]]

[[7 8]
 [7 8]]

[[1 2 7 8]
 [3 4 7 8]]


In [13]:
# height
import numpy as np
var1= np.array([[1,2],[3,4]])
var2= np.array([[7,8],[7,8]])
ar=np.dstack((var1,var2))# h stack is height
print(var1)

print()
print(var2)
print()

print(ar)

[[1 2]
 [3 4]]

[[7 8]
 [7 8]]

[[[1 7]
  [2 8]]

 [[3 7]
  [4 8]]]


# [iii] split(break )

In [17]:
import numpy as np

var1 = np.array([1, 2, 3, 4, 5, 6])
print(var1)

ar = np.array_split(var1, 3)   # corrected 'var' → 'var1'

print()
print(ar)
print()

print(ar[0])# index


[1 2 3 4 5 6]

[array([1, 2]), array([3, 4]), array([5, 6])]

[1 2]


In [18]:

var1 = np.array([[1, 2],[ 3, 4], [5, 6]])
print(var1)
ar = np.array_split(var1, 3)   # corrected 'var' → 'var1'

print()
print(ar)
print()

print(ar[0])# index


[[1 2]
 [3 4]
 [5 6]]

[array([[1, 2]]), array([[3, 4]]), array([[5, 6]])]

[[1 2]]


#  -----Search sort search soted filter function

In [19]:
import numpy as np
var = np.array([1,2,3,4,5,2,3,5])
print(var)
print()
x= np.where(var==2)# not repeat value
print(x)

[1 2 3 4 5 2 3 5]

(array([1, 5], dtype=int64),)


In [20]:
import numpy as np
var = np.array([1,2,3,4,5,2,3,5])
print(var)
print()
x= np.where(var%2)# “var array me wo numbers kaha par hain jo odd
print(x)

[1 2 3 4 5 2 3 5]

(array([0, 2, 4, 6, 7], dtype=int64),)


# [i] search sorted array

In [24]:
import numpy as np
var = np.array([1,2,3,4,5,2,3,5])
x1= np.searchsorted(var,5,side = "left")# index value
print(x1)

4


In [25]:
import numpy as np
var = np.array([1,2,3,4,5,2,3,5])
x1= np.searchsorted(var,5,side = "right")# index value
print(x1)

8


In [ ]:
# douth

# -----suffle unique Resize Flatten ravel function

# [i] suffle


In [31]:
import numpy as np
var = np.array([1,2,3,4,5])
np.random.shuffle(var)# number change
print(var)
print()
print(var)

[1 5 4 3 2]

[1 5 4 3 2]


# [ii] unique

In [33]:
import numpy as np
var = np.array([2,5,1,9,5,56,3])
x= np.unique(var)# siquance form
print(var)
print()
print(x)

[ 2  5  1  9  5 56  3]

[ 1  2  3  5  9 56]


# [iii] Resize

In [36]:
import numpy as np

var = np.array([1, 2, 3, 4, 5, 6])
ar = np.resize(var, (2, 3))   # 2 row aur 3 column me resize kiya
print(ar)


[[1 2 3]
 [4 5 6]]


# [iv] flatten

In [ ]:
flatten() kya karta hai?

flatten() ek NumPy function hai jo
 multi-dimensional array (2D, 3D, etc.) ko 1D array me badal deta hai.

Yani — “array ko seedha line me kar deta hai”.

In [38]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

flat = arr.flatten()
print(arr)
print()
print(flat)



[[1 2 3]
 [4 5 6]]

[1 2 3 4 5 6]


# insert and Delete function

In [ ]:
# np.insert() kya karta hai?

#  np.insert() ka kaam hota hai array me naya element daalna (insert karna)
# kisi particular position (index) par.


# syntax 
# np.insert(array, position, value)


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
new_arr = np.insert(arr, 2, 99)# array ,position value
print(new_arr)


In [39]:
# 0 axis row
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
new_arr = np.insert(arr, 2, 99,axis= 0)# array ,position value
print(new_arr)

[ 1  2 99  3  4  5]


In [44]:
arr = np.array([1, 2, 3, 4, 5]).reshape(-1, 1)  # 5x1 column
new_arr = np.insert(arr, 1, 99, axis=1)
print(new_arr)


[[ 1 99]
 [ 2 99]
 [ 3 99]
 [ 4 99]
 [ 5 99]]


# [ii] append

In [45]:
import numpy as np

arr = np.array([1, 2, 3])
new_arr = np.append(arr, 4)
print(new_arr)


[1 2 3 4]


# 2D array

In [47]:
arr = np.array([[1, 2], [3, 4]])
new_arr = np.append(arr, [[7],[8]])  # axis=1 → column add
print(new_arr)


[[1 2 7]
 [3 4 8]]


# 3D array

In [48]:
arr = np.array([[1, 2], [3, 4]])
new_arr = np.append(arr, [[5, 6]], axis=0)  # axis=0 → row add
print(new_arr)


[[1 2]
 [3 4]
 [5 6]]


# [iii] Delete

In [49]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
new_arr = np.delete(arr, 2)  # 2nd index delete
print(new_arr)


[1 2 4 5]


#  2D array

In [50]:
arr = np.array([[1, 2], [3, 4], [5, 6]])
new_arr = np.delete(arr, 1, axis=0)  # 1st row delete
print(new_arr)


[1 2 4 5]


# -------matrix numpy  array 

# transpose

In [ ]:
# [] [] -----|| column and row ek colum pura raow


In [57]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print(arr)
print()
print(np.transpose(arr))
#print(transposed)


[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]


# swapaxes

In [ ]:
#  row --columns
# column----row


# swapaxes() kya karta hai?

#  swapaxes() ka kaam hota hai array ke do axes (dimensions) ko ek dusre ke saath swap karna.

# Matlab:

# 2D me → rows aur columns ko swap karna (transpose ka kaam karta hai)

# 3D+ me → do axes ko interchange karna

# 🔹 Syntax:
# np.swapaxes(array, axis1, axis2)

In [58]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

swapped = np.swapaxes(arr, 0, 1)#swapaxes(arr, 0, 1) → rows aur columns swap ho gaye
print(swapped)


[[1 4]
 [2 5]
 [3 6]]


# inverse

In [ ]:
# np.linalg.inv() kya karta hai?

#  inverse() ka kaam hota hai matrix ka ulta (inverse) nikalna.

# Sirf square matrix (rows = columns) ka inverse hota hai.

# Agar matrix ka determinant 0 ho → inverse exist nahi karta.

# 🔹 Syntax:
# np.linalg.inv(matrix)

# Part	Matlab
# matrix	Jo square matrix hai jiska inverse chahiye

In [62]:
import numpy as np

A = np.array([[1, 2],
              [3, 4]])

inv_A = np.linalg.inv(A)
print(inv_A)


[[-2.   1. ]
 [ 1.5 -0.5]]


# power

In [ ]:
# np.power() kya karta hai?

# power() ka kaam hota hai array ke elements ka exponentiation karna.

# Matlab: har element ko kisi number se power (ghat) me badalna

# 🔹 Syntax:
# np.power(array, exponent)

# Part	Matlab
# array	Jo array ke elements ko raise karna hai
# exponent	Kaunsa power lagana hai

In [63]:
import numpy as np

arr = np.array([1, 2, 3, 4])
new_arr = np.power(arr, 2)  # square karna
print(new_arr)


[ 1  4  9 16]


# 2D array

In [64]:
arr2 = np.array([[1, 2],
                 [3, 4]])

new_arr = np.power(arr2, 2)
print(new_arr)


[[ 1  4]
 [ 9 16]]


# Determinate

In [ ]:
# Determinant kya hai?

# Determinant ek square matrix ke liye ek number hai jo matrix ke properties ke baare me batata hai:

# Agar determinant = 0 → matrix invertible nahi hai

# Agar determinant ≠ 0 → matrix invertible hai

# 🔹 NumPy me Syntax:
# np.linalg.det(matrix)

# Part	Matlab
# matrix	Jo square matrix ka determinant chahiye

In [65]:
import numpy as np

A = np.array([[1, 2],
              [3, 4]])

det_A = np.linalg.det(A)
print(det_A)


-2.0000000000000004
