In [1]:
# numpy>> numerical python
# 2005 by travis oliphant

#Python ki ek powerful library hai jo numbers, arrays aur mathematical operations ke liye use hoti hai. 
# Python ki ek powerful library hai jo numbers, arrays aur mathematical operations ke liye use hoti hai.
# Data Science, AI, ML, Image Processing sab jagah NumPy ka use hota hai.

In [3]:
import numpy as np
np.__version__

'1.26.4'

In [4]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly 

In [1]:
list = [1,2,"complex",3+5j]

In [2]:
type(list)

list

In [3]:
list

[1, 2, 'complex', (3+5j)]

In [1]:
 # Numpy  stores the data in an array
# An array is a container used to stored the data of same type

In [8]:
import numpy as np
l = [1,2,3,4,5]
arr = np.array(l)
arr

array([1, 2, 3, 4, 5])

In [9]:
l = [1,2,3,4,5.6]
arr = np.array(l)
arr

array([1. , 2. , 3. , 4. , 5.6])

In [10]:
# string is stores
l = [1,2,3,4,5.6,"sonu"]
arr = np.array(l)
arr

array(['1', '2', '3', '4', '5.6', 'sonu'], dtype='<U32')

In [11]:
# array stores is homogenous data
type(arr)# ndarray ---n dimension array

numpy.ndarray

In [12]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [13]:
arr.ndim

2

# matrix

In [14]:
mat = np.matrix([1,2,3,4])
type(mat)

numpy.matrix

In [15]:
mat

matrix([[1, 2, 3, 4]])

In [2]:
 # more to convert array 
import numpy as np
l =[1,2,3]
np.asarray(l)

array([1, 2, 3])

In [4]:
# more than convert to array
np.asanyarray([1,2,3])

array([1, 2, 3])

# tupple array

In [5]:
tup = ([2,3,4,56],[6,7,8,9])
type(tup)

tuple

In [6]:
np.array(tup)

array([[ 2,  3,  4, 56],
       [ 6,  7,  8,  9]])

# index 

In [7]:
l= [1,2,3,4,5]
arr = np.array(l)

In [8]:
arr

array([1, 2, 3, 4, 5])

In [9]:
arr[0] =500 # index

In [10]:
arr

array([500,   2,   3,   4,   5])

In [11]:
a =arr

In [12]:
a

array([500,   2,   3,   4,   5])

In [ ]:
# shallow ccopy -- change is other array not define is create array

In [13]:
# not change is [a]
arr[0]= 10000
arr

array([10000,     2,     3,     4,     5])

In [14]:
 arr[0]=30000

In [15]:
arr

array([30000,     2,     3,     4,     5])

In [ ]:
# define --- create array [np.array ] [np.asanyarray] [deep copyis shallow array]

# multiple way to generate array

In [25]:
arr1=np.fromfunction(lambda  i, j:i==j,(4,4))
arr1

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [26]:
np.fromfunction(lambda  i, j:i==j,(2,2))

array([[ True, False],
       [False,  True]])

In [27]:
arr1.ndim # Number of Dimensions

2

In [28]:
arr1.shape #shap of array

(4, 4)

In [29]:
arr1.size # total element

16

In [30]:
# using by multiple
arr2=np.fromfunction(lambda  i, j:i*j,(4,4))
arr2

array([[0., 0., 0., 0.],
       [0., 1., 2., 3.],
       [0., 2., 4., 6.],
       [0., 3., 6., 9.]])

In [32]:
for i in range(5):
    print(i)

0
1
2
3
4


In [33]:
[i for i in range(5)]

[0, 1, 2, 3, 4]

In [34]:
[m for m in range(5)]

[0, 1, 2, 3, 4]

In [35]:
[i*i for i in range(5)]


[0, 1, 4, 9, 16]

In [37]:
list((i for i in range(5)))

[0, 1, 2, 3, 4]

In [38]:
iterable = (i for i in range(5))

In [39]:
np.fromiter(iterable, int)# variable ,int------# createa new 1 demensional from an iterable object

array([0, 1, 2, 3, 4])

# fromstring

In [43]:
np.fromstring('34 45 78', sep = " ")  


array([34., 45., 78.])

In [48]:
np.fromstring('34, 45, 78', sep = ",") 

array([34., 45., 78.])

In [44]:
string = "sonu, monu,abhi"
string1 = string.split(',')
np.array(string1)

array(['sonu', ' monu', 'abhi'], dtype='<U5')

In [49]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [51]:
range(10)

range(0, 10)

# (start, stop, step)

In [52]:
# othermethod of numpyto generate squnce of 
np.arange(1,10,0.1) #(start, stop, step)

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2,
       2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5,
       3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8,
       4.9, 5. , 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1,
       6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4,
       7.5, 7.6, 7.7, 7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7,
       8.8, 8.9, 9. , 9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

In [53]:
np.arange(1, 10, 2)


array([1, 3, 5, 7, 9])

In [55]:
# othermethod of numpyto generate squnce of 
np.linspace(1,5,10)#given me 10 number between 1to 5 evenlyspace

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [56]:
# np.logspace() logarithmic scale par numbers generate karta hai
#Matlab numbers power (exponent) ke form me hote hain.

# start = 1 → 10¹

# stop = 5 → 10⁵

# num = 10 → 10 numbers chahiye


np.logspace(1,5,10)

array([1.00000000e+01, 2.78255940e+01, 7.74263683e+01, 2.15443469e+02,
       5.99484250e+02, 1.66810054e+03, 4.64158883e+03, 1.29154967e+04,
       3.59381366e+04, 1.00000000e+05])

In [57]:
np.logspace(1,5,10,base=2)

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])

# Advance 1

# zeros

In [58]:
a= np.zeros(5)

In [59]:
a

array([0., 0., 0., 0., 0.])

In [60]:
a.ndim

1

In [62]:
b = np.zeros((3,4))
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [63]:
b.ndim

2

In [65]:
c =np.ones((3,4))
c

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [66]:
np.twos(5)# does not exist

AttributeError: module 'numpy' has no attribute 'twos'

In [67]:
arr1 = np.array([[1,2,3,4],[5,6,8,9]])
arr1

array([[1, 2, 3, 4],
       [5, 6, 8, 9]])

In [68]:
arr1.ndim

2

# 3 dimensional array

In [69]:
np.zeros(1)

array([0.])

In [70]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [71]:
arr1= np.zeros((1,3,4))# (Depth, Rows, Columns) depth-- layer


In [72]:
arr1

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [73]:
arr1.ndim

3

In [74]:
arr2= np.ones((3,4))

In [75]:
arr2.ndim

2

In [76]:
arr2.size

12

In [77]:
arr2.shape

(3, 4)

In [78]:
arr2 +5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [79]:
arr2*5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [80]:
arr2-1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [81]:
np.eye(3)# all element is diogonal

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [84]:
np.eye(3, dtype =int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [85]:
np.empty((3,4))#Return anew arrayofgivenand typewithoutinitiallzing entries

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

 # optional  >>random number

In [92]:
import random 
random.choice((1,2,3,4,5))

4

In [93]:
random.choice("Ajay")

'A'

In [94]:
random.randrange(1,10)

6

In [95]:
random.random()# random no is generatet between 0(incluide) and1 (excluded)

0.10102659782595391

In [98]:
lis = [1,2,3,4,5]
lis

[1, 2, 3, 4, 5]

In [99]:
random.shuffle(lis)# listarandom number

In [100]:
lis

[1, 5, 2, 4, 3]

In [101]:
random.uniform(7,14)# uniform --har point equal chance

13.15944351318169

In [102]:
# random number related concept in array
np.array([])

array([], dtype=float64)

In [103]:
np.random.random_sample()

0.4887938270768094

In [104]:
np.random.random_sample(5)

array([0.79474295, 0.12165824, 0.00754567, 0.81089296, 0.97554765])

# random.rand

In [105]:
np.random.rand(1)

array([0.32530176])

In [106]:
np.random.rand(2,4)

array([[0.45241417, 0.51304807, 0.89045455, 0.45313162],
       [0.19794919, 0.68750701, 0.74034192, 0.5353341 ]])

# random.randn

In [108]:
np.random.randn(2,3)#subtraction

array([[ 1.10381142, -0.26198353, -0.78049942],
       [ 1.4909756 ,  0.70592752,  0.55113693]])

# random.randint

In [111]:
array = np.random.randint(1,5,size= (3,4))# size (row , collumn)

In [112]:
array.ndim

2

In [113]:
array.shape

(3, 4)

In [114]:
array.size

12

# Reshaping the array

In [118]:
# Reshaping ka matlab hota hai:
# 👉 Array ka shape change karna, bina data badle.

In [119]:
import numpy as np

a = np.array([1, 2, 3, 4, 5, 6])
b = a.reshape(2, 3)
print(b)


[[1 2 3]
 [4 5 6]]


In [120]:
b.size

6

In [121]:
b.shape

(2, 3)

In [122]:
arr  = np.array(([1,2,3,4,5,6]))
c = arr.reshape(2,3)
c

array([[1, 2, 3],
       [4, 5, 6]])

In [123]:
arr  = np.array(([1,2,3,4,5,6]))
c = arr.reshape(1,6)
c

array([[1, 2, 3, 4, 5, 6]])

In [124]:
arr  = np.array(([1,2,3,4,5,6]))
c = arr.reshape(6,1)
c

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [127]:
arr  = np.array(([1,2,3,4,5,6]))
c = arr.reshape(3,-1)
c

array([[1, 2],
       [3, 4],
       [5, 6]])

In [4]:
import numpy as np
arr = np.array([[1,3,3,4],[4,3,3,3],[4,4,1,4]])
arr

array([[1, 3, 3, 4],
       [4, 3, 3, 3],
       [4, 4, 1, 4]])

In [5]:
arr.reshape(2,6)

array([[1, 3, 3, 4, 4, 3],
       [3, 3, 4, 4, 1, 4]])

In [6]:
arr.shape

(3, 4)

In [7]:
arr.size

12

In [8]:
# array size not change always resape parameter should be multipication of origninal array size
arr

array([[1, 3, 3, 4],
       [4, 3, 3, 3],
       [4, 4, 1, 4]])

In [9]:
arr.size

12

In [10]:
arr.reshape(2,6)

array([[1, 3, 3, 4, 4, 3],
       [3, 3, 4, 4, 1, 4]])

In [11]:
arr.reshape(1,12)

array([[1, 3, 3, 4, 4, 3, 3, 3, 4, 4, 1, 4]])

In [12]:
arr.reshape(12,1)

array([[1],
       [3],
       [3],
       [4],
       [4],
       [3],
       [3],
       [3],
       [4],
       [4],
       [1],
       [4]])

In [13]:
# case when youdont in reshape what shouldbethecolumn count
arr.reshape(4,-1)

array([[1, 3, 3],
       [4, 4, 3],
       [3, 3, 4],
       [4, 1, 4]])

In [14]:
arr.reshape(2,-1)

array([[1, 3, 3, 4, 4, 3],
       [3, 3, 4, 4, 1, 4]])

In [16]:
arr.reshape(-2,4)# -2 is not force issystem

array([[1, 3, 3, 4],
       [4, 3, 3, 3],
       [4, 4, 1, 4]])

In [17]:
arr.reshape(12,1).base# see is a orignals values arr

array([[1, 3, 3, 4],
       [4, 3, 3, 3],
       [4, 4, 1, 4]])

In [19]:
arr.reshape(2,2,3)

array([[[1, 3, 3],
        [4, 4, 3]],

       [[3, 3, 4],
        [4, 1, 4]]])

In [20]:
arr.reshape(3,2,2)# multipication 2*2*3

array([[[1, 3],
        [3, 4]],

       [[4, 3],
        [3, 3]],

       [[4, 4],
        [1, 4]]])

In [21]:
# (1, 2, 2, 3)
#  ↑  ↑  ↑  ↑
#  |  |  |  |
#  |  |  |  └─ 3 elements
#  |  |  └──── 2 rows
#  |  └─────── 2 blocks
#  └────────── 1 sample / batch

arr.reshape(1,2,2,3)


array([[[[1, 3, 3],
         [4, 4, 3]],

        [[3, 3, 4],
         [4, 1, 4]]]])

In [22]:
arr.reshape(4,3,1) # 4 time  3 row 1 column

array([[[1],
        [3],
        [3]],

       [[4],
        [4],
        [3]],

       [[3],
        [3],
        [4]],

       [[4],
        [1],
        [4]]])

In [24]:
arr1 = np.random.randint(1,10,(5,6))
arr1

array([[5, 8, 9, 8, 8, 5],
       [8, 4, 9, 3, 6, 8],
       [8, 9, 6, 7, 4, 1],
       [9, 6, 5, 9, 6, 5],
       [1, 3, 2, 3, 7, 9]])

In [25]:
arr1.ndim

2

In [26]:
arr1.size

30

In [27]:
arr1.shape

(5, 6)

In [28]:
arr1>1

array([[ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False],
       [ True,  True,  True,  True,  True,  True],
       [False,  True,  True,  True,  True,  True]])

In [29]:
arr1[arr1>3] # less than

array([5, 8, 9, 8, 8, 5, 8, 4, 9, 6, 8, 8, 9, 6, 7, 4, 9, 6, 5, 9, 6, 5,
       7, 9])

In [30]:
  arr1[arr1<3]

array([1, 1, 2])

# array indexing

In [31]:
arr1

array([[5, 8, 9, 8, 8, 5],
       [8, 4, 9, 3, 6, 8],
       [8, 9, 6, 7, 4, 1],
       [9, 6, 5, 9, 6, 5],
       [1, 3, 2, 3, 7, 9]])

In [32]:
to access element in the array
arr1[0]

array([5, 8, 9, 8, 8, 5])

In [33]:
# count element
arr1[1][0]#  row number is countelement

8

In [34]:
arr1[1]

array([8, 4, 9, 3, 6, 8])

In [35]:
arr1

array([[5, 8, 9, 8, 8, 5],
       [8, 4, 9, 3, 6, 8],
       [8, 9, 6, 7, 4, 1],
       [9, 6, 5, 9, 6, 5],
       [1, 3, 2, 3, 7, 9]])

# slicing

In [36]:
arr1[0:2] # one is  less

array([[5, 8, 9, 8, 8, 5],
       [8, 4, 9, 3, 6, 8]])

In [37]:
arr1[0:3]

array([[5, 8, 9, 8, 8, 5],
       [8, 4, 9, 3, 6, 8],
       [8, 9, 6, 7, 4, 1]])

In [38]:
arr1[0:3,[0,1]]# ek se three column is calculate ---[0,1] zero row 1 coumn is find

array([[5, 8],
       [8, 4],
       [8, 9]])

In [40]:
arr1[0:3 ,1:3]

array([[8, 9],
       [4, 9],
       [9, 6]])

In [41]:
arr[0,[1,3]]

array([3, 4])

In [46]:
arr1 = np.random.randint(1,3,(3,3))
arr2 = np.random.randint(1,3,(3,3))

In [47]:
arr1

array([[1, 2, 2],
       [1, 1, 2],
       [1, 1, 1]])

In [48]:
arr2

array([[1, 1, 2],
       [1, 1, 2],
       [2, 1, 2]])

# addition

In [49]:
arr1+arr2

array([[2, 3, 4],
       [2, 2, 4],
       [3, 2, 3]])

# substraction

In [50]:
arr1-arr2

array([[ 0,  1,  0],
       [ 0,  0,  0],
       [-1,  0, -1]])

# multipication

In [51]:
arr1*arr2

array([[1, 2, 4],
       [1, 1, 4],
       [2, 1, 2]])

# division

In [55]:
arr1/arr2

array([[1. , 2. , 1. ],
       [1. , 1. , 1. ],
       [0.5, 1. , 0.5]])

In [56]:
# matrix multiplication differentindexwise multiplicatio

arr1 @ arr2# ---arr1 @ arr2  =  matrix multiplication

array([[ 7,  5, 10],
       [ 6,  4,  8],
       [ 4,  3,  6]])

In [57]:
# or-- same data 
np.dot(arr1,arr2)

array([[ 7,  5, 10],
       [ 6,  4,  8],
       [ 4,  3,  6]])

In [58]:
arr1/0

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_17760\1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [59]:
a = np.array([1,2,3,4])

In [60]:
# Transpose
a.T

array([1, 2, 3, 4])

In [61]:
arr1.T

array([[1, 1, 1],
       [2, 1, 1],
       [2, 2, 1]])

In [62]:
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.41421356],
       [1.        , 1.        , 1.41421356],
       [1.        , 1.        , 1.        ]])

In [63]:
np.log10(arr1)

array([[0.     , 0.30103, 0.30103],
       [0.     , 0.     , 0.30103],
       [0.     , 0.     , 0.     ]])

In [64]:
np.exp(arr1)

array([[2.71828183, 7.3890561 , 7.3890561 ],
       [2.71828183, 2.71828183, 7.3890561 ],
       [2.71828183, 2.71828183, 2.71828183]])

In [65]:
np.min(arr1)

1

In [66]:
np.max(arr1)

2

In [2]:
import numpy as np

In [3]:
arr1 =np.random.randint(1,3, (3,3))
arr2 =np.random.randint(1,3, (3,3))

In [4]:
arr1

array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2]])

In [5]:
arr1.flatten()# return a copy is thearray collopsedintoone dimension

array([1, 1, 1, 1, 1, 1, 2, 2, 2])

# expand_dims --axis(0 row 1 columns)

In [6]:
# expand dimension
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [7]:
np.expand_dims(arr,axis =  0)# create the row dimension

array([[1, 2, 3, 4]])

In [8]:
np.expand_dims(arr,axis =  1)

array([[1],
       [2],
       [3],
       [4]])

In [9]:
np.expand_dims(arr,axis =  0).ndim

2

In [10]:
arr

array([1, 2, 3, 4])

In [13]:
arr1 = np.zeros((3,4))
arr1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
np.expand_dims(arr1,axis = 0)

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [15]:
np.expand_dims(arr1,axis = 1)

array([[[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]]])

# squeeze--Remove axes of lenght one from 

In [21]:
a = np.array([[1],[2],[3]])
a

array([[1],
       [2],
       [3]])

In [22]:
a.ndim

2

In [23]:
np.squeeze(a)# brackets is remove

array([1, 2, 3])

# Repeat

In [24]:
rep = np.array([1,2,3,4])
rep

array([1, 2, 3, 4])

In [25]:
np.repeat(rep,4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4])

In [26]:
a

array([[1],
       [2],
       [3]])

In [27]:
np.repeat(a,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [28]:
np.repeat(a,2,axis = 0)

array([[1],
       [1],
       [2],
       [2],
       [3],
       [3]])

In [29]:
np.repeat(a,2,axis = 1)

array([[1, 1],
       [2, 2],
       [3, 3]])

# roll-- number rotate(not fixed number)

In [32]:
arr1 =np.array([[1],[2],[3],[4],[5],[6]])
arr1

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [33]:
np.roll(arr1,-3)

array([[4],
       [5],
       [6],
       [1],
       [2],
       [3]])

In [34]:
c = np.array([[1,2],[3,4],[6,7],[9,5]])
c

array([[1, 2],
       [3, 4],
       [6, 7],
       [9, 5]])

In [35]:
np.roll(c,-1)

array([[2, 3],
       [4, 6],
       [7, 9],
       [5, 1]])

# operation on numpy string array

# [i] char.upper

In [36]:
d = np.array(["sonu","kushwaha"])
d

array(['sonu', 'kushwaha'], dtype='<U8')

In [37]:
np.char.upper(d)

array(['SONU', 'KUSHWAHA'], dtype='<U8')

# [ii] char.capitalize

In [38]:
np.char.capitalize(d)

array(['Sonu', 'Kushwaha'], dtype='<U8')

# mathematical function

# sin

In [40]:
arr1 = np.array([[1,2,3],[4,5,6],[9,0,5]])
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [9, 0, 5]])

In [41]:
np.sin(arr1)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ],
       [ 0.41211849,  0.        , -0.95892427]])

In [42]:
np.cos(arr1)

array([[ 0.54030231, -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029],
       [-0.91113026,  1.        ,  0.28366219]])

In [43]:
np.log10(arr1)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_20792\2590435965.py:1: RuntimeWarning: divide by zero encountered in log10
  np.log10(arr1)


array([[0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125],
       [0.95424251,       -inf, 0.69897   ]])

In [44]:
np.exp(arr1)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [8.10308393e+03, 1.00000000e+00, 1.48413159e+02]])

In [45]:
np.power(arr1,3)

array([[  1,   8,  27],
       [ 64, 125, 216],
       [729,   0, 125]], dtype=int32)

In [46]:
np.min(arr1)

0

In [47]:
np.max(arr1)

9

In [48]:
np.std(arr1)

2.601044424604361

In [50]:
np.var(arr1)

6.765432098765432

In [53]:
a = np.array([[1,2,3],[7,8,9],[9,4,0]])
b = np.array([[1,4,5],[8,5,7],[4,7,6]])

In [54]:
a

array([[1, 2, 3],
       [7, 8, 9],
       [9, 4, 0]])

In [55]:
b

array([[1, 4, 5],
       [8, 5, 7],
       [4, 7, 6]])

In [56]:
c = a+b
c

array([[ 2,  6,  8],
       [15, 13, 16],
       [13, 11,  6]])

In [57]:
e =a-b
e

array([[ 0, -2, -2],
       [-1,  3,  2],
       [ 5, -3, -6]])

In [60]:
np.subtract(a,b)

array([[ 0, -2, -2],
       [-1,  3,  2],
       [ 5, -3, -6]])

In [58]:
f = a-b
f

array([[ 0, -2, -2],
       [-1,  3,  2],
       [ 5, -3, -6]])

In [59]:
g = a*b
g

array([[ 1,  8, 15],
       [56, 40, 63],
       [36, 28,  0]])

In [61]:
np.multiply(a,b)

array([[ 1,  8, 15],
       [56, 40, 63],
       [36, 28,  0]])

In [62]:
np.mod(a,b)# returnelment remainder

array([[0, 2, 3],
       [7, 3, 2],
       [1, 4, 0]])

In [63]:
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081],
       [2.64575131, 2.82842712, 3.        ],
       [3.        , 2.        , 0.        ]])

# sort

In [64]:
e = np.array([1,7,3,7,9,5,6])
e

array([1, 7, 3, 7, 9, 5, 6])

In [65]:
np.sort(e)

array([1, 3, 5, 6, 7, 7, 9])

In [66]:
f = np.array([5,199,6,7,8])
f

array([  5, 199,   6,   7,   8])

In [67]:
np.sort(f)

array([  5,   6,   7,   8, 199])

In [68]:
np.searchsorted(f,8)

4

In [69]:
np.searchsorted(f,199)

5

# count nonzeros

# Array me jitne elements ZERO (0) nahi hain unki ginti karta hai.

# Zero nahi = non-zero

In [72]:
f =np.array([1,3,89,0,67,5,7,4])
f

array([ 1,  3, 89,  0, 67,  5,  7,  4])

In [74]:
np.count_nonzero(f)

7

In [76]:
np.sort(f)

array([ 0,  1,  3,  4,  5,  7, 67, 89])

In [78]:
g =np.array ([5,199,200,6,7,0,0,0,8])
g

array([  5, 199, 200,   6,   7,   0,   0,   0,   8])

In [79]:
np.count_nonzero(g)

6

In [82]:
f[f > 0]

array([ 1,  3, 89, 67,  5,  7,  4])

# where --Condition ke base par position (index) ya value batata hai.

In [83]:
marks = np.array([35, 60, 28, 80])
result = np.where(marks >= 33, "Pass", "Fail")
result

array(['Pass', 'Pass', 'Fail', 'Pass'], dtype='<U4')

In [84]:
np.where (f>0)

(array([0, 1, 2, 4, 5, 6, 7], dtype=int64),)

# extract----Condition ke base par values nikalta hai (sirf values, index nahi).

In [85]:
np.extract(f>0,f)

array([ 1,  3, 89, 67,  5,  7,  4])

In [86]:
import numpy as np

arr = np.array([1, 4, 6, 2, 9])
np.extract(arr > 4, arr)


array([6, 9])

# byteswap----Number ke bytes ka order ulta kar deta hai

In [87]:
f

array([ 1,  3, 89,  0, 67,  5,  7,  4])

In [89]:
# 256 = 01 00
# byteswap → 00 01
# 00 01 = 1

f.byteswap()

array([  16777216,   50331648, 1493172224,          0, 1124073472,
         83886080,  117440512,   67108864])

# matrix>> 2d array

In [90]:
import numpy.matlib as nm

In [91]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [93]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

# linear algebra

# formula

In [ ]:
|a b|
|c d| = ad − bc


    = (1×4) − (2×3)
= 4 − 6
= -2



Index = d*(R*C) + r*C + c
d = block number (0 se start)

R = rows per block

C = columns per row

r = row number

c = column number

Matlab: block → row → column ke hisaab se flat memory index nikalta hai


arr = np.array([
    [[1, 2, 3],       # Block 0, Row 0
     [4, 5, 6]],      # Block 0, Row 1

    [[7, 8, 9],       # Block 1, Row 0
     [10, 11, 12]]    # Block 1, Row 1
])
Shape = (2, 2, 3) → D=2, R=2, C=3
d*(R*C) + r*C 
arr[0,0,0] = 0*(2*3) + 0*3 + 0 = 0  → value 1
arr[0,0,1] = 0*(2*3) + 0*3 + 1 = 1  → value 2
arr[0,0,2] = 0*(2*3) + 0*3 + 2 = 2  → value 3

arr[0,1,0] = 0*(2*3) + 1*3 + 0 = 3  → value 4
arr[0,1,1] = 0*(2*3) + 1*3 + 1 = 4  → value 5
arr[0,1,2] = 0*(2*3) + 1*3 + 2 = 5  → value 6


In [94]:
# numpy liner algebra
arr1 = np.random.randint(1,10,(3,3))
arr2 = np.random.randint(1,10,(3,3))

In [95]:
arr1

array([[6, 2, 3],
       [3, 2, 4],
       [9, 4, 1]])

In [96]:
arr2

array([[4, 9, 8],
       [4, 4, 8],
       [6, 2, 2]])

In [97]:
# @ = row × column ka multiplication
arr1 @ arr2

array([[ 50,  68,  70],
       [ 44,  43,  48],
       [ 58,  99, 106]])

In [99]:
np.linalg.det(arr1)

-36.000000000000014

In [100]:
np.linalg.inv(arr1)

array([[ 0.38888889, -0.27777778, -0.05555556],
       [-0.91666667,  0.58333333,  0.41666667],
       [ 0.16666667,  0.16666667, -0.16666667]])

In [101]:
a =  np.array([[7,5.3,-3],[3,-5,2],[5,3,-7]])

In [102]:
a

array([[ 7. ,  5.3, -3. ],
       [ 3. , -5. ,  2. ],
       [ 5. ,  3. , -7. ]])

In [103]:
b = np.array([16,8,0])
b

array([16,  8,  0])

In [104]:
np.linalg.solve(a,b)

array([2.59630607, 0.84432718, 2.21635884])

In [ ]:
🔹 Exam Tips

Determinant → np.linalg.det()

Inverse → np.linalg.inv()

Matrix multiplication → @ or np.dot()

Transpose → .T

Rank → np.linalg.matrix_rank()

Eigenvalues / Eigenvectors → np.linalg.eig()


7x+6y+5z = 6

7x+6y+5z = 6

conert the matrix [7 6 5]   6
                   7 6 5    6